# Generated by Django 6.0.2 on 2026-05-10 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0002_alter_maestro_sexo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Documento de Identidad')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
                ('edad', models.PositiveIntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('barrio', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('telefono_habitacion', models.CharField(max_length=20)),
                ('telefono_movil', models.CharField(max_length=20)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('ocupacion', models.CharField(max_length=100)),
                ('telefono_trabajo', models.CharField(max_length=20)),
                ('email_trabajo', models.EmailField(max_length=254)),
                ('disciplina', models.CharField(choices=[('motocross', 'Motocross'), ('motovelocidad', 'Motovelocidad'), ('enduro', 'Enduro'), ('trial', 'Trial'), ('supermotard', 'Supermotard'), ('cuatrimotos', 'Cuatrimotos'), ('motos_calle', 'Motos de Calle'), ('atv', 'ATV'), ('carros_4x4', 'Carros 4x4')], max_length=50)),
                ('horario_entrenamiento', models.JSONField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('grupo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('alergias', models.BooleanField(default=False)),
                ('alergias_especifique', models.TextField(blank=True, null=True)),
                ('padecimientos', models.BooleanField(default=False)),
                ('padecimientos_especifique', models.TextField(blank=True, null=True)),
                ('tratamiento_medico', models.BooleanField(default=False)),
                ('tratamiento_especifique', models.TextField(blank=True, null=True)),
                ('toma_medicamento', models.BooleanField(default=False)),
                ('medicamento_forma_suministro', models.TextField(blank=True, null=True)),
                ('seguro_medico', models.BooleanField(default=False)),
                ('seguro_especifique', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aprobada', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='maestro',
            name='escuela',
        ),
        migrations.CreateModel(
            name='PerfilMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_aplicacion.solicitud')),
            ],
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Escuela',
        ),
        migrations.DeleteModel(
            name='Maestro',
        ),
    ]
