# Generated by Django 6.0.2 on 2026-05-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0003_solicitud_remove_maestro_escuela_perfilmiembro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='acepta_fotografias',
            field=models.BooleanField(default=False, verbose_name='Acepto el Permiso de Fotografías'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='acepta_privacidad',
            field=models.BooleanField(default=False, verbose_name='Acepto la Política de Privacidad'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='acepta_responsabilidad',
            field=models.BooleanField(default=False, verbose_name='Acepto la Liberación de Responsabilidad Social'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='documentos_vehiculo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Adjuntar Documentos del Vehículo'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='emergencia2_apellidos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellidos (2do Contacto)'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='emergencia2_codigo_tel',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código Tel. (2do)'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='emergencia2_nombres',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombres (2do Contacto)'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='emergencia2_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número de Teléfono (2do)'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='emergencia_apellidos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellidos (Contacto Emergencia)'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='emergencia_barrio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='emergencia_ciudad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='emergencia_codigo_tel',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código Tel.'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='emergencia_direccion',
            field=models.TextField(blank=True, verbose_name='Dirección de Residencia'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='emergencia_nombres',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombres (Contacto Emergencia)'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='emergencia_pais',
            field=models.CharField(blank=True, max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='emergencia_parentesco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Parentesco'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='emergencia_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número de Teléfono'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='firma_conformidad',
            field=models.TextField(blank=True, null=True, verbose_name='Firma de Conformidad'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='foto_identificacion',
            field=models.FileField(blank=True, null=True, upload_to='identificaciones/', verbose_name='Adjuntar Foto de Identificación'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='moto_modelo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Moto Modelo'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='moto_placa',
            field=models.CharField(blank=True, max_length=20, verbose_name='Moto Placa'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='vehiculo_modelo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vehículo Modelo'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='vehiculo_placa',
            field=models.CharField(blank=True, max_length=20, verbose_name='Vehículo Placa'),
        ),
    ]
