# Generated by Django 6.0.2 on 2026-05-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0005_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='documentos_vehiculo',
            field=models.FileField(default='', upload_to='documentos/', verbose_name='Adjuntar Documentos del Vehículo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_identificacion',
            field=models.FileField(default='', upload_to='identificaciones/', verbose_name='Adjuntar Foto de Identificación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='moto_modelo',
            field=models.CharField(max_length=100, verbose_name='Moto Modelo'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='moto_placa',
            field=models.CharField(max_length=20, verbose_name='Moto Placa'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='vehiculo_modelo',
            field=models.CharField(max_length=100, verbose_name='Vehículo Modelo'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='vehiculo_placa',
            field=models.CharField(max_length=20, verbose_name='Vehículo Placa'),
        ),
    ]
