# Generated by Django 6.0.2 on 2026-05-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0006_alter_solicitud_documentos_vehiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilmiembro',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
