# Generated by Django 6.0.2 on 2026-05-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0007_perfilmiembro_nombre_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilmiembro',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='perfilmiembro',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AddField(
            model_name='perfilmiembro',
            name='ig_user',
            field=models.CharField(blank=True, max_length=50, verbose_name='Usuario de Instagram'),
        ),
        migrations.AddField(
            model_name='perfilmiembro',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
