# Generated by Django 6.0.2 on 2026-05-12 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0008_perfilmiembro_descripcion_perfilmiembro_foto_perfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilmiembro',
            name='ig_user',
        ),
    ]
